import Link from "next/link"
import "./globals.css";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by gyumingim",
};

export default async function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header>
          <nav>
            <div className="wrap">
              <div className="logo_wrap wrap">
                <img src="/peake_logo_title.png" className="logo"/>
              </div>
              <div className="a_wrap wrap">
                <a className="new_pair_a a" href="/new_pair">신규</a>
                <a className="popular_a a" href="/popular">인기</a>
                <a className="ranking_a a" href="/ranking">랭킹</a>
                <a className="investment_a a" href="/investment">투자내역</a>
              </div>
            </div>
            <div className="search_wrap wrap">
              <input className="search_box" placeholder="유튜버 검색"/>
            </div>
            <div className="login_wrap wrap">
              <input className="login_button" type="button" value={"로그인"}  />
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
